[book]
authors = ["Saplyn Miao"]
language = "en"
src = "src"
title = "Saplyn's Notebook"

[output.html]
site-url = "/notebook/"
fold = { enable = true }
git-repository-url = "https://github.com/Saplyn/notebook"
edit-url-template = "https://github.com/Saplyn/notebook/edit/main/{path}"
